import { Footer, Header } from "@/components";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "@/styles/reset.css";
import "@/styles/root.scss";
import "@/styles/globals.scss";
import classNames from "classnames";
import { ROBOTO, RUBIK, ZILLA_SLAB } from "@/config";

export const metadata: Metadata = {
  title: "Pokemon world",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  const fonts = classNames(RUBIK.variable, ROBOTO.variable, ZILLA_SLAB.variable);
  return (
    <html lang="en">
      <body className={fonts}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
